project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, Jenna Furtado" 
    right: 
      - icon: github
        href: https://github.com/
  title: "Jenna's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - Map_Walkthrough.qmd
      - undergraduate_thesis.qmd
      - news_story_example.qmd
      - 01_virginia_election_project_datawrangling.qmd
      - 02_virginia_election_project_youranalysis.qmd
    
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



