---
title: News Story Writing Sample
---

The story below was written for my Introduction to News Writing and Reporting Class. The assignment to write a feature piece about an event going on in the DMV area. I chose to write about the D.C. Pride Parade, and interviewed several folks that attended the parade about what it meant to them. I also examined the history of pride parades in D.C. and probed opinions about the corporatization of pride month. The story is located below:

Thousands of people filled the streets of Washington D.C. Logan and DuPont Circle neighborhoods this weekend for the annual pride parade--the first in-person parade since 2019.

"It feels amazing! My girlfriend and I have been together for 3 years and we've been waiting to celebrate pride together so it's really meaningful." George Washington University (GWU) graduate Caroline Frentz exclaimed.

The parade took place Saturday, June 11, 2022 from 3 p.m. to 7 p.m. Floats sponsored by various organizations glided through the streets, met with cheering crowds. Music blared, people danced, and excitement emanated from the air. It was a joyous celebration. In the past year, many states passed anti-LGBTQ+ legislation, which made the celebration of queer joy more important than ever.

"The parade is important to me because it is all of us demanding space in public to be queer, which is so powerful and beautiful." Allyson Bonhaus, a GWU student and member of the LGBT+ community said.

Though Pride is celebrated throughout the US with events like festivals and parades, it originated from the 1969 Stonewall riots in New York City. Washington D.C. native Joey Crittenden commented on how they felt Capital Pride honored the memories of those who came before.

"The pride parades that exist today should honor Marsha P. Johnson, Silvia Rivera, and other trans women and what we would probably now consider trans men at Stonewall." They explained their complicated feelings about how the parade honored their memory, expressing discomfort at the integration of cops and corporations into the parade due to their testy relationship with the LGBTQ+ community. "At pride, we have families, we have adults, we have drag queens, we have kink, we have bisexual couples, gay couples, other queer couples, people that are there by themselves, teenagers, people of all ages and I think that's really wonderful. That does help honor their memory." Crittenden concluded.

Pride in D.C. originated from a one day celebration in 1971. From there, it expanded to the annual Gay Pride Day starting in 1975. The parade became part of the celebration in 1981, the same year the name changed to Gay and Lesbian Pride Day. Finally, the event changed to Capital Pride in 1997 when the Whitman-Walker Clinic joined as a co-sponsor and now features a whole weekend of activities celebrating pride.

" Pride cannot be boiled down into a simple definition, but it is a celebration first and foremost to me---a celebration of us, of all the ones who couldn't be at the parade, and all those who came before and after us to continue making this pride happen and continue. Pride is a recognition of queer history, queer accomplishments, and queer joy." Bonhaus said.

Another GWU student and ally to the LGBTQ+ community, Kaitlyn Yuan, chimed in. "I think it most of all represents solidarity, love, and acceptance..."

Her sentiments were reflected by GWU graduate Alexandra "Alex" Lay, who said: "Pride to me is the ability to feel proud about a chosen identity that may not fit the societal norm."

Pride is meaningful to many members of D.C.'s LGBTQ+ community, bringing them together to remember their history and look towards the future. Crittenden emphasized: "Community is really important. It's not just about what infrastructure there is, but also about interpersonal connections...that is what community truly is and that's what pride does. It brings so many people together..."

The pride parade is a space for joy and remembrance. As Yuan put it, "Pride is so so important especially right with the regression on women's rights and that legislation on queer folks...now is the best time ever to give all the support, inclusivity, love...knowing that people care and are willing to dedicate time towards their efforts."
